server:
  port: 8211

spring:
  application:
    name: business-demo-zipkin
  datasource:
    url: jdbc:mysql://localhost:3306/spdise?useUnicode=true&amp&characterEncoding=utf-8&useSSL=false
    driverclassname: com.mysql.jdbc.Driver
    username: root
    password: 123456

management:
  metrics:
    web:
      server:
        auto-time-requests: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8227/eureka/