server:
  port: 8271

spring:
  application:
    name: business-qingyuan
  elasticsearch:
    jest:
      uris: http://127.0.0.1:9200
      connection-timeout: 10000
      read-timeout: 10000
  # zipkin 配置
  #  zipkin:
  #    base-url: http://localhost:8211
  #  sleuth:
  #    sampler:
  #      #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）
  #      probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/qingyuan?useUnicode=true&amp&characterEncoding=utf-8&useSSL=false
    driverclassname: com.mysql.jdbc.Driver
    username: root
    password: 123456
  freemarker:
    suffix: .html
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
#  redis:
#    database: 0         #Redis数据库索引（默认为0）
#    host: 127.0.0.1
#    port: 6379
#    password:
#    timeout: 30000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8227/eureka/

mybatis:
  mapper-locations: classpath*:mapper/*.xml

# 显示 sql 语句
logging:
  level:
    com:
      jh:
        business:
          base:
            mapper: debug

# rocketMq 配置
spdise:
  rocketMq:
    nameServerAddr: 127.0.0.1:9876
    producerMaxRetryCount: 10
    consumeMaxRetryCount: 10
